### ISSUE TITLE
version must not be included when zero

### ISSUE THREAD

**Issue by job** [APNIC-net/rpki-rsc-demo#3]
Hi Tom,

A RSC generated by the APNIC demo - where the `version` field is set - looks like this:

```
    0:d=0  hl=2 l=  75 cons: SEQUENCE
    2:d=1  hl=2 l=   3 cons:  cont [ 0 ]
    4:d=2  hl=2 l=   1 prim:   INTEGER           :00      <-- THE VERSION
    7:d=1  hl=2 l=   8 cons:  SEQUENCE
    9:d=2  hl=2 l=   6 cons:   cont [ 0 ]
   11:d=3  hl=2 l=   4 cons:    SEQUENCE
   13:d=4  hl=2 l=   2 prim:     INTEGER           :3CCA
   17:d=1  hl=2 l=  11 cons:  SEQUENCE
   19:d=2  hl=2 l=   9 prim:   OBJECT            :sha256
   30:d=1  hl=2 l=  45 cons:  SEQUENCE
   32:d=2  hl=2 l=  43 cons:   SEQUENCE
   34:d=3  hl=2 l=   7 prim:    IA5STRING         :content
   43:d=3  hl=2 l=  32 prim:    OCTET STRING
      0000 - d6 f3 c0 ad aa 9e 8d 7b-a3 1b b6 89 be 5d c2 28   .......{.....].(
      0010 - 36 a8 0f 0e 50 91 84 e8-86 19 03 d3 4f 46 63 11   6...P.......OFc.
```

however, from X.690, 11.5:
>   The encoding of a set value or a sequence value shall not include an
>   encoding for any component value which is equal to its default value.

In other words: it MUST NOT be included if it is zero.

The validator I am working on will error if it sees a zero version field (or any version field)

Can you please take a look at this? What is your take?

Kind regards,

Job

**Comment by benmaddison** [comment]
@job your reading of the spec agrees with my understanding. Any correct deserializer generated from the ASN.1 type def will choke on this.

**Comment by tomhrr** [comment]
Thanks all, I think your readings are correct, and this has been fixed now.
